#pragma once

#ifndef ORIENTEDQUADQUADRANT_H
#define ORIENTEDQUADQUADRANT_H

enum class OrientedQuadQuadrant
{
	YPLANE_POSX_POSZ,
	YPLANE_NEGX_POSZ,
	YPLANE_NEGX_NEGZ,
	YPLANE_POSX_NEGZ,
	XPLANE_POSY_POSZ,
	XPLANE_POSY_NEGZ,
	XPLANE_NEGY_NEGZ,
	XPLANE_NEGY_POSZ,
	ZPLANE_POSX_POSY,
	ZPLANE_NEGX_POSY,
	ZPLANE_NEGX_NEGY,
	ZPLANE_POSX_NEGY,
	NONE
};

#endif
