#pragma once

#ifndef TwoDLineSegmentINTERSECTTYPE_H
#define TwoDLineSegmentINTERSECTTYPE_H

enum class TwoDLineSegmentIntersectType
{
	COLINEAR,
	COLINEAR_OVERLAP,
	COLINEAR_NOOVERLAP,
	PARALLEL,
	NONCOLINEAR_INTERSECT,
	NONCOLINEAR_INTERSECTS_POINT_PRECISE,
	T_JUNCTION_A_SPLITS_B_VIA_POINT_A,
	T_JUNCTION_A_SPLITS_B_VIA_POINT_B,
	T_JUNCTION_B_SPLITS_A_VIA_POINT_A,
	T_JUNCTION_B_SPLITS_A_VIA_POINT_B,
	NO_INTERSECT,
	NOVAL
};

#endif
