#pragma once

#ifndef TwoDLineSegmentINTERSECTTYPE_H
#define TwoDLineSegmentINTERSECTTYPE_H

enum class TwoDLineSegmentIntersectType
{
	COLINEAR_OVERLAP,
	COLINEAR_NOOVERLAP,
	PARALLEL,
	NONCOLINEAR_INTERSECT,
	NONCOLINEAR_INTERSECTS_POINT_PRECISE,
	NO_INTERSECT,
	NOVAL
};

#endif
