#pragma once
#ifndef TWODPOLYINTERSECTIONTYPE_H
#define TWODPOLYINTERSECTIONTYPE_H

enum class TwoDSPolyIntersectionType
{
	HIT_BORDERLINE,
	HIT_NONBORDERLINE,
	PRECISE_HIT_BORDERLINE,
	PRECISE_HIT_NONBORDERLINE,
	NO_HIT,
	NOVAL
};

#endif
